config/routes.rb
Blog::Application.routes.draw do |map|
  resources :posts do
    resources :comments
  end

  root :to => "posts#index"
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :author
  field :email
  field :body
  embedded_in :post, :inverse_of => :comments
end

app/models/post.rb
class Post
  include Mongoid::Document
  field :title
  field :body
  embeds_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/astaire_controller.rb
class AstaireController < ApplicationController
  get "/help" do
    render :text => "this is the help docs"
  end

  get '/yes-this-is-the-sinatra-dsl-in-rails' do
    render :text => "omgwtfbbq"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.build params[:comment]
    if @comment.save
      redirect_to [post]
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html
  respond_to :rss, :only => [:index]

  def index
     respond_with(@posts = Post.all)
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new params[:post]
    if @post.save
      flash[:notice] = "post was created"
      respond_to do |wants|
        wants.html { redirect_to posts_path }
        wants.js
      end
    end
  end

  def show
    @post = Post.find params[:id]
    @comment = @post.comments.build
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag "formtastic" %>
    <%= stylesheet_link_tag "formtastic_changes" %>
    <%= javascript_include_tag "jquery-1.4.2.min.js", "rails.js"%>
    <%= javascript_include_tag "application.js" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/notifier/new_edition.html.erb
<% url = post_url(@post, 
                  :host => "b.example.com") %>

<html>
	<body>
		<p>Hello my friend <%= @address%></p>
		<p>
			We have a new blog post titled, 
			"<%= @post.title %>", that we're 
			sure you'll enjoy reading.  Why not 
			read it at 
			<%= link_to url, url %>.
		</p>
	</body>
</html>

app/views/posts/create.js.erb
$('#quick_post').slideUp('slow');
$('#quick_post form')[ 0 ].reset();
$('#posts').append("<li><%= escape_javascript(link_to @post.title, [@post]) %>");
$('#posts li:last').effect("highlight", {}, 3000);

app/views/posts/index.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<div id="quick_post">
  <%= semantic_form_for Post.new, :remote => true do |f| %>
    <%= f.inputs do %>
      <%= f.input :title %>
      <%= f.input :body %>
    <% end %>
    <%= f.buttons do %>
      <%= f.commit_button "Create", :button_html => {:disable_with => "Creating..."} %>
    <% end %>
  <% end %>
</div>

<ul id="posts">
  <% @posts.each do |post|%>
    <li><%= link_to post.title, [post] %></li>
  <% end %>
</ul>

<%= link_to "Create a new post", new_post_path %>

app/views/posts/new.html.erb
<%= semantic_form_for @post do |f| %>
  <%= f.inputs do %>
    <%= f.input :title %>
    <%= f.input :body %>
  <% end %>
  <%= f.buttons do %>
    <%= f.commit_button :label => "Create" %>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= div_for @post do %>
  <%= @post.body %>
<% end %>

<% if @post.comments %>
  <div id="comments" do %>
      <% @post.comments.each do |comment| %>
        <%= div_for comment do %>
          <dl>
            <dt>Author</dt>
            <dd><%= comment.author %></td> 
            <dt>Comment</dt>
            <dd><%= comment.body %></td> 
          </dl>
        <% end %>
      <% end %>
  </div>
<% end %>

<div id="comment">
  <%= semantic_form_for @comment, :url => [@post, :comments] do |f| %>
    <%= f.inputs do %>
      <%= f.input :email %>
      <%= f.input :author, :label => "Name" %>
      <%= f.input :body, :label => "Comment" %>
    <% end %>
    <%= f.buttons do %>
      <%= f.commit_button :label => "Submit my comment" %>
    <% end %>
  <% end %>
</div>